apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: {{ .Values.service.type}}
  selector:
    app: nginx
    tier: frontend
  ports:
  - name: nginx-svc-port
    port: {{ .Values.service.port}}
    protocol: TCP
    targetPort: 80