#install helm:
# curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
# chmod 700 get_helm.sh
# ./get_helm.sh
# to check, helm version


apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  labels:
    app: mysql
    tier: db
    project: expense
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: mysql
      tier: db
      project: expense
  template:
    metadata:
      name: mysql
      labels:
        app: mysql
        tier: db
        project: expense
    spec:
      containers:
      - name: mysql
        image: mysql:{{ .Values.deployment.imageVersion }}

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: expense
spec:
  selector:
    app: mysql
    tier: db
    project: expense
  ports:
  - name: mysql-svc-port
    protocol: TCP
    port: 3306
    targetPort: {{ .Values.service.targetPort}}