apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: expense
spec:
  type: {{ .Values.service.type }}
  selector:
    app: frontend
    tier: web
    project: expense
  ports:
  - name: frontend-svc-port
    protocol: TCP
    port: 80
    targetPort: 80